nome = str(input('Digite seu nome: ')).strip()
primeiroNome = nome.split()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é {};'.format(nome.upper()))
print('Seu nome em letras minúsculas é {};'.format(nome.lower()))
print('Seu nome ao todo tem {} letras;'.format(len(nome)-nome.count((' '))))
print('Seu primeiro nome é {} e ele tem {} letras'.format(primeiroNome[0], len(primeiroNome[0])))